spring.application.name=ordenescompra
server.port=8081

# ── Oracle Cloud ──────────────────────────────────────────────────────────────
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=C##DSY2201
spring.datasource.password=DSY2201_$
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ── JPA / Hibernate ───────────────────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# ── HATEOAS ───────────────────────────────────────────────────────────────────
spring.hateoas.use-hal-as-default-json-media-type=true
